version: '3'
services:
  nginx-file-browser:
    image: nginx:latest
    container_name: nginx-file-browser
    ports:
      - "5000:80"
    volumes:
      - ./files:/host-files:ro                 # Mount host directory (as read-only)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx configuration (as read-only)
    restart: always
