
services:  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-app

  my-app:
    container_name: my-app
    image: mendhak/http-https-echo:30
    environment:
        - HTTP_PORT=8888